### ISSUE TITLE
support file select in dropdown

### ISSUE THREAD

**Issue by tehho** [codecontemplator/vscode-kubeseal#3]
When sealing a file it would be nice to have the option of file select from current workspace. 

This also goes for the cert select.

**Comment by codecontemplator** [comment]
Implemented file pickers for certificate in v 0.0.3. Not sure about file selectors for the secret files. Closing for now. Reopen another issue if it feels important.

**Comment by codecontemplator** [comment]
New ui btw:

![image](https://user-images.githubusercontent.com/3386085/79049145-f5edf880-7c21-11ea-8e92-f02550a5c89e.png)
