### ISSUE TITLE
Which versions are supported?

### ISSUE THREAD

**Issue by iremmats** [codecontemplator/vscode-kubeseal#4]
Unable to install 'codecontemplator.kubeseal' extension because it is not compatible with the current version of VS Code (version 1.41.1).

Unable to install 'codecontemplator.kubeseal' extension because it is not compatible with the current version of VS Code (version 1.42.0).

**Comment by codecontemplator** [comment]
Was never able to reproduced this issue. Please have a go again with the latest version of the extension and re-open if you still have problems.
